var JABLES_CONSTANTS = {};

JABLES_CONSTANTS.SORT_BY_CHOICES = {};
JABLES_CONSTANTS.SORT_BY_CHOICES.DEFUALT = "Default";
JABLES_CONSTANTS.SORT_BY_CHOICES.LOWEST_PRICE = "Lowest Price";
JABLES_CONSTANTS.SORT_BY_CHOICES.HIGHEST_PRICE = "Highest Price";
JABLES_CONSTANTS.SORT_BY_CHOICES.LOCATION = "Location";

JABLES_CONSTANTS.PRICE_CHOICES = {};
JABLES_CONSTANTS.PRICE_CHOICES.ANY = "Any";
JABLES_CONSTANTS.PRICE_CHOICES.FREE = "Free";
JABLES_CONSTANTS.PRICE_CHOICES.DOLLAR_1 = "$";
JABLES_CONSTANTS.PRICE_CHOICES.DOLLAR_2 = "$$";
JABLES_CONSTANTS.PRICE_CHOICES.DOLLAR_3 = "$$$";
JABLES_CONSTANTS.PRICE_CHOICES.DOLLAR_4 = "$$$$";


selectedEvent = {};

selectedVenue = {};